name: Lint, Build and Deploy Website
on:
  push:
    branches:
      - master
    paths:
      - "**"

jobs:
  lint-build-deploy:
    # generates static files in dest folder
    name: Lint and Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: yarn install --frozen-lockfile
      - run: yarn build
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      - uses: cpina/github-action-push-to-another-repository@v1.3
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: "dest"
          destination-github-username: "jkguidaven"
          destination-repository-name: "jkguidaven.github.io"
          user-email: jkguidaven@gmail.com
